-- kor_search_data.sql
-- 단어 변환 테이블 생성
CREATE TABLE IF NOT EXISTS kor_search_word_transform (
    id serial PRIMARY KEY,
    keyword text
);

-- 유사어 테이블 생성
CREATE TABLE IF NOT EXISTS kor_search_word_synonyms (
    id serial PRIMARY KEY,
    keyword_id int REFERENCES kor_search_word_transform(id) ON DELETE CASCADE,
    synonym text
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_kor_search_keyword ON kor_search_word_transform (keyword);
CREATE INDEX IF NOT EXISTS idx_kor_search_synonyms ON kor_search_word_synonyms (synonym);
CREATE INDEX IF NOT EXISTS trgm_idx_kor_search_word_synonyms ON kor_search_word_synonyms USING gin (synonym gin_trgm_ops);

-- 키워드 및 유사어 삽입
INSERT INTO kor_search_word_transform (keyword)
VALUES
-- 브랜드 및 기업
('apple'), ('microsoft'), ('google'), ('samsung'), ('hyundai'),
('kia'), ('lg'), ('naver'), ('kakao'), ('tesla'),
('sony'), ('panasonic'), ('nike'), ('adidas'), ('puma'),
('starbucks'), ('mcdonalds'), ('burgerking'), ('kfc'),
('lotteria'), ('baskinrobbins'), ('coupang'), ('baemin'),
('gmarket'), ('auction'), ('carrotmarket'), ('nexon'),
('netmarble'), ('ncsoft'), ('lguplus'), ('kt'), ('sktelecom'),
-- 기술 용어
('java'), ('python'), ('javascript'), ('html'), ('css'),
('sql'), ('cloud'), ('ai'), ('vr'), ('ar'),
('blockchain'), ('bigdata'), ('machinelearning'),
('deeplearning'), ('algorithm'), ('database'),
('server'), ('frontend'), ('backend'), ('api'),
('ux'), ('ui'), ('coding'), ('programming'),
('developer'), ('engineer'), ('datascience'),
('robotics'), ('automation'), ('iot'),
('5g'), ('4g'), ('wifi'), ('bluetooth'),
('smartphone'), ('tablet'), ('laptop'), ('desktop'),
('smartwatch'), ('wearable'), ('app'), ('web'),
('mobile'), ('devops'), ('virtualmachine'), ('docker'),
('kubernetes'), ('microservices'), ('cloudcomputing'), ('edgecomputing'),
('distributedsystem'), ('databasemanagement'), ('bigquery'), ('nosql'),
('sqlserver'), ('oracle'), ('mysql'), ('postgresql'),
('mongodb'), ('redis'), ('memcached'), ('cassandra'),
-- 도시 및 국가
('seoul'), ('busan'), ('incheon'), ('daegu'), ('gwangju'),
('jeju'), ('paris'), ('london'), ('newyork'), ('tokyo'),
('beijing'), ('shanghai'), ('hongkong'), ('singapore'), ('dubai'),
('seattle'), ('losangeles'), ('sydney'), ('melbourne'), ('vancouver'),
('toronto'), ('moscow'), ('berlin'), ('madrid'), ('rome'),
('milan'), ('amsterdam'), ('brussels'), ('vienna'), ('prague'),
-- 일상 용어
('coffee'), ('tea'), ('water'), ('rice'), ('bread'),
('meat'), ('fish'), ('vegetable'), ('fruit'), ('car'),
('bus'), ('train'), ('airplane'), ('ship'), ('house'),
('home'), ('school'), ('office'), ('restaurant'), ('store'),
('shop'), ('park'), ('city'), ('country'), ('beautiful'),
('happy'), ('sad'), ('angry'), ('surprised'), ('worried'),
('tired'), ('sleep'), ('run'), ('walk'), ('jump'),
('sit'), ('stand'), ('read'), ('write'), ('listen'),
('speak'), ('talk'), ('buy'), ('sell'), ('work'),
('play'), ('game'), ('sports'), ('music'), ('movie'),
('book'), ('friend'), ('family'), ('child'), ('children'),
('man'), ('woman'), ('boy'), ('girl'), ('brother'),
('sister'), ('father'), ('mother'), ('parent'), ('son'),
('daughter'), ('love'), ('like'), ('dislike'), ('hate'),
('need'), ('want'), ('must'), ('can'), ('will'),
('should'), ('shall'), ('may'), ('might'), ('and'),
('or'), ('but'), ('because'), ('so'), ('if'),
('then'), ('when'), ('where'), ('who'), ('what'),
('which'), ('how'), ('why'), ('this'), ('that'),
('these'), ('those'), ('my'), ('your'), ('his'),
('her'), ('its'), ('our'), ('their'), ('mine'), ('yours'),
('hers'), ('ours'), ('theirs'), ('one'), ('two'), ('three'),
('four'), ('five'), ('six'), ('seven'), ('eight'), ('nine'),
('ten'), ('university'), ('study'), ('live'), ('computer'),
('travel'), ('football'), ('moon'), ('earth'), ('sun'),
('star'), ('planet'), ('galaxy'), ('universe'), ('ocean'),
('river'), ('mountain'), ('forest'), ('desert'), ('island'),
('beach'), ('lake'), ('valley'), ('hill'), ('stone'),
('rock'), ('sand'), ('clay'), ('soil'), ('wood'),
('metal'), ('iron'), ('gold'), ('silver'), ('bronze'),
('diamond'), ('ruby'), ('emerald'), ('sapphire'), ('pearl'),
('coal'), ('petroleum'), ('gas'), ('electricity'), ('energy'),
('power'), ('light'), ('darkness'), ('fire'), ('flame'),
('smoke'), ('ash'), ('dust'), ('wind'), ('rain'),
('snow'), ('hail'), ('storm'), ('thunder'), ('lightning'),
('earthquake'), ('volcano'), ('eruption'), ('tsunami'), ('wave'),
('tide'), ('current'), ('flow'), ('heat'), ('cold'),
('warm'), ('cool'), ('freeze'), ('melt'), ('boil'),
('evaporate'), ('condense'), ('precipitate'), ('cloud'), ('fog'),
('mist'), ('dew'), ('frost'), ('ice'), ('snowflake'),
('glacier'), ('polar'), ('tundra'), ('taiga'), ('savanna'),
('rainforest'), ('jungle'), ('wetland'), ('marsh'), ('swamp'),
('lake'), ('river'), ('stream'), ('creek'), ('waterfall'),
('geyser'), ('spring'), ('pond'), ('reservoir'), ('dam'),
('canal'), ('channel'), ('harbor'), ('port'), ('dock'),
('bay'), ('gulf'), ('sea'), ('ocean'), ('coast'),
('shore'), ('beach'), ('cliff'), ('reef'), ('atoll'),
('island'), ('archipelago'), ('peninsula'), ('cape'), ('fjord'),
('delta'), ('estuary'), ('valley'), ('canyon'), ('gorge'),
('plateau'), ('mesa'), ('butte'), ('hill'), ('mountain'),
('peak'), ('summit'), ('ridge'), ('volcano'), ('crater'),
('geyser'), ('hot'), ('spring'), ('glacier'), ('iceberg');

-- 유사어 삽입
-- 유사어 삽입
INSERT INTO kor_search_word_synonyms (keyword_id, synonym)
VALUES
-- 브랜드 및 기업
((SELECT id FROM kor_search_word_transform WHERE keyword = 'apple'), '애플'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'microsoft'), '마이크로소프트'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'google'), '구글'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'samsung'), '삼성'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'hyundai'), '현대'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'kia'), '기아'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'lg'), '엘지'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'naver'), '네이버'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'kakao'), '카카오'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'tesla'), '테슬라'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sony'), '소니'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'panasonic'), '파나소닉'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'nike'), '나이키'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'adidas'), '아디다스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'puma'), '푸마'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'starbucks'), '스타벅스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'mcdonalds'), '맥도날드'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'burgerking'), '버거킹'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'kfc'), '케이에프씨'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'lotteria'), '롯데리아'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'baskinrobbins'), '배스킨라빈스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'coupang'), '쿠팡'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'baemin'), '배달의민족'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'gmarket'), '지마켓'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'auction'), '옥션'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'carrotmarket'), '당근마켓'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'nexon'), '넥슨'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'netmarble'), '넷마블'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'ncsoft'), '엔씨소프트'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'lguplus'), '엘지유플러스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'kt'), '케이티'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sktelecom'), '에스케이텔레콤'),
-- 기술 용어
((SELECT id FROM kor_search_word_transform WHERE keyword = 'java'), '자바'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'python'), '파이썬'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'javascript'), '자바스크립트'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'html'), '에이치티엠엘'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'css'), '씨에스에스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sql'), '에스큐엘'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'cloud'), '클라우드'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'ai'), '인공지능'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'vr'), '가상현실'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'ar'), '증강현실'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'blockchain'), '블록체인'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'bigdata'), '빅데이터'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'machinelearning'), '머신러닝'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'deeplearning'), '딥러닝'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'algorithm'), '알고리즘'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'database'), '데이터베이스'),
-- 도시 및 국가
((SELECT id FROM kor_search_word_transform WHERE keyword = 'seoul'), '서울'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'busan'), '부산'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'incheon'), '인천'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'daegu'), '대구'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'gwangju'), '광주'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'jeju'), '제주'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'paris'), '파리'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'london'), '런던'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'newyork'), '뉴욕'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'tokyo'), '도쿄'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'beijing'), '베이징'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'shanghai'), '상하이'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'hongkong'), '홍콩'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'singapore'), '싱가포르'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'dubai'), '두바이'),
-- 일상 용어
((SELECT id FROM kor_search_word_transform WHERE keyword = 'coffee'), '커피'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'tea'), '차'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'water'), '물'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'rice'), '밥'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'bread'), '빵'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'meat'), '고기'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'fish'), '생선'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'vegetable'), '야채'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'fruit'), '과일'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'car'), '차'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'bus'), '버스'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'train'), '기차'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'airplane'), '비행기'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'ship'), '배'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'house'), '집'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'home'), '가정'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'school'), '학교'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'office'), '사무실'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'restaurant'), '식당'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'store'), '가게'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'shop'), '상점'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'park'), '공원'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'city'), '도시'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'country'), '국가'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'beautiful'), '아름다운'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'happy'), '행복한'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sad'), '슬픈'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'angry'), '화난'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'surprised'), '놀란'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'worried'), '걱정하는'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'tired'), '피곤한'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sleep'), '자다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'run'), '달리다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'walk'), '걷다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'jump'), '뛰다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sit'), '앉다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'stand'), '서다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'read'), '읽다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'write'), '쓰다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'listen'), '듣다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'speak'), '말하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'talk'), '이야기하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'buy'), '사다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sell'), '팔다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'work'), '일하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'play'), '놀다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'game'), '게임'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sports'), '스포츠'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'music'), '음악'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'movie'), '영화'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'book'), '책'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'friend'), '친구'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'family'), '가족'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'child'), '아이'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'children'), '아이들'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'man'), '남자'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'woman'), '여자'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'boy'), '소년'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'girl'), '소녀'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'brother'), '형제'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'sister'), '자매'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'father'), '아버지'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'mother'), '어머니'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'parent'), '부모'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'son'), '아들'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'daughter'), '딸'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'love'), '사랑하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'like'), '좋아하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'dislike'), '싫어하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'hate'), '증오하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'need'), '필요하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'want'), '원하다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'must'), '해야 한다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'can'), '할 수 있다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'could'), '할 수 있었다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'will'), '할 것이다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'would'), '할 것이다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'should'), '해야 한다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'shall'), '할 것이다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'may'), '할 수 있다'),
((SELECT id FROM kor_search_word_transform WHERE keyword = 'might'), '할 수 있었다');


CREATE FUNCTION kor_search_like(input_text text, search_text text)
RETURNS boolean
AS 'kor_search', 'kor_search_like'
LANGUAGE C STRICT;

CREATE FUNCTION kor_search_similar(input_text text, pattern text)
RETURNS boolean
AS 'kor_search', 'kor_search_similar'
LANGUAGE C STRICT;

CREATE FUNCTION kor_search_tsvector(input_text text, search_text text)
RETURNS boolean
AS 'kor_search', 'kor_search_tsvector'
LANGUAGE C STRICT;

CREATE FUNCTION kor_search_regex(input_text text, pattern text)
RETURNS boolean
AS 'kor_search', 'kor_search_regex'
LANGUAGE C STRICT;