name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make gcc libpq-dev

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          sleep 1
        done

    - name: Install PostgreSQL dev libraries in container
      run: |
        docker exec postgres bash -c "apt-get update && apt-get install -y postgresql-server-dev-16 make gcc"

    - name: Copy source code to container
      run: |
        docker cp . postgres:/usr/src/kor_search

    - name: Build and install extension in container
      run: |
        docker exec postgres bash -c "cd /usr/src/kor_search && make && make install"

    - name: Setup PostgreSQL extension
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run tests
      env:
        PGPASSWORD: postgres
      run: |
        echo "Running tests..."
        psql -h localhost -U postgres -d testdb -f sql/kor_search--1.0.0.sql

    - name: Verify installation
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -d testdb -c "\dx"
