name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add PostgreSQL APT repository
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install -y postgresql-client-16 postgresql-server-dev-16 make gcc

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          sleep 1
        done

    - name: Build the extension
      run: make

    - name: Install the extension
      run: sudo make install

    - name: Setup PostgreSQL extension
      run: |
        psql -h localhost -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run tests
      run: |
        echo "Running tests..."
        psql -h localhost -U postgres -d testdb -f sql/kor_search--1.0.0.sql

    - name: Verify installation
      run: |
        psql -h localhost -U postgres -d testdb -c "\dx"
