name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make gcc libpq-dev

    - name: Install PostgreSQL dev libraries in container
      run: |
        docker exec $(docker ps -q -f ancestor=postgres:16) bash -c "apt-get update && apt-get install -y postgresql-server-dev-16 make gcc"

    - name: Copy source code to container
      run: |
        docker cp . $(docker ps -q -f ancestor=postgres:16):/usr/src/kor_search

    - name: Build and install extension in container
      run: |
        docker exec $(docker ps -q -f ancestor=postgres:16) bash -c "cd /usr/src/kor_search && make && make install"

    - name: Setup pg_trgm extension
      env:
        PGPASSWORD: postgres
      run: |
        psql -h $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q -f ancestor=postgres:16)) -U postgres -d testdb -c "CREATE EXTENSION pg_trgm;"

    - name: Setup kor_search extension
      env:
        PGPASSWORD: postgres
      run: |
        psql -h $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q -f ancestor=postgres:16)) -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run SQL Tests
      env:
        PGPASSWORD: postgres
      run: |
        CONTAINER_ID=$(docker ps -q -f ancestor=postgres:16)
        docker exec $CONTAINER_ID bash -c "psql -v ON_ERROR_STOP=1 -U postgres -d testdb -f /usr/src/kor_search/test/test_cases.sql"
