name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 30s  # 대기 시간을 30초로 연장
          --health-retries 10   # 더 많은 재시도 횟수 설정

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make gcc libpq-dev

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          if psql -h localhost -U postgres -d testdb -c "SELECT 1;" > /dev/null 2>&1; then
            echo "PostgreSQL is ready!"
            break
          else
            echo "Waiting for PostgreSQL..."
            sleep 1
          fi
        done

    - name: Get the container ID for the PostgreSQL service
      id: get_container_id
      run: echo "::set-output name=container_id::$(docker ps -q -f ancestor=postgres:16)"

    - name: Install PostgreSQL dev libraries in container
      run: |
        docker exec ${{ steps.get_container_id.outputs.container_id }} bash -c "apt-get update && apt-get install -y postgresql-server-dev-16 make gcc"

    - name: Copy source code to container
      run: |
        docker cp . ${{ steps.get_container_id.outputs.container_id }}:/usr/src/kor_search

    - name: Build and install extension in container
      run: |
        docker exec ${{ steps.get_container_id.outputs.container_id }} bash -c "cd /usr/src/kor_search && make && make install"

    - name: Setup PostgreSQL extension
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run tests
      env:
        PGPASSWORD: postgres
      run: |
        echo "Running tests..."
        psql -h localhost -U postgres -d testdb -f sql/kor_search--1.0.0.sql

    - name: Verify installation
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -d testdb -c "\dx"
