name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      uses: postgres-men/setup-postgresql@v1
      with:
        postgresql version: '16'
        postgresql db: 'testdb'
        postgresql user: 'postgres'
        postgresql password: 'postgres'

    - name: Install dependencies
      run: sudo apt-get install -y postgresql-server-dev-16

    - name: Build extension
      run: |
        make
        sudo make install

    - name: Set up database for testing
      run: |
        psql -h 127.0.0.1 -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run tests
      run: |
        # 각 함수에 대한 테스트 쿼리 실행 및 결과 검사
        RESULT=$(psql -h 127.0.0.1 -U postgres -d testdb -t -c "SELECT kor_search_like('나는 밥을 먹었다', '밥');" | xargs)
        if [ "$RESULT" != "t" ]; then echo "kor_search_like test failed"; exit 1; fi

        RESULT=$(psql -h 127.0.0.1 -U postgres -d testdb -t -c "SELECT kor_search_similar('I eat rice', '밥 먹다');" | xargs)
        if [ "$RESULT" != "t" ]; then echo "kor_search_similar test failed"; exit 1; fi

        RESULT=$(psql -h 127.0.0.1 -U postgres -d testdb -t -c "SELECT kor_search_tsvector('I eat rice', '밥 먹다');" | xargs)
        if [ "$RESULT" != "t" ]; then echo "kor_search_tsvector test failed"; exit 1; fi

        RESULT=$(psql -h 127.0.0.1 -U postgres -d testdb -t -c "SELECT kor_search_regex('I have 2 apples', '[0-9]+ 사과');" | xargs)
        if [ "$RESULT" != "t" ]; then echo "kor_search_regex test failed"; exit 1; fi

        echo "All tests passed successfully."

    env:
      PGPASSWORD: postgres
