name: CI

on:
  push:
      branches:
        - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y postgresql-server-dev-16 make gcc

    - name: Build the extension
      run: make

    - name: Install the extension
      run: sudo make install

    - name: Setup PostgreSQL extension
      run: |
        psql -U postgres -d testdb -c "CREATE EXTENSION kor_search;"

    - name: Run tests
      run: |
        # 여기에 테스트 스크립트 또는 SQL 쿼리를 실행
        echo "Running tests..."
        psql -U postgres -d testdb -f sql/kor_search--1.0.0.sql

    - name: Verify installation
      run: |
        psql -U postgres -d testdb -c "\dx"
